language: node_js
branches:
  only:
      - master
node_js:
  - "8"
script: npm run-script deploy
addons:
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
env:
  global:
    - CXX=g++-4.8
    - GH_REF: github.com/ryanvalentin/housewolf-studio.git
    - secure: $GITHUB_PERSONAL_TOKEN
